// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGdFyWoYOSSYhGMMt-dz_cUwakm4jPt0',
    appId: '1:432650534768:web:a4fc53643510b5dc4519b5',
    messagingSenderId: '432650534768',
    projectId: 'home-care-fb5a7',
    authDomain: 'home-care-fb5a7.firebaseapp.com',
    storageBucket: 'home-care-fb5a7.appspot.com',
    measurementId: 'G-DCXCC13957',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVUr12Xzm1062yd-EV8aXAfNBdQf4XMcM',
    appId: '1:432650534768:android:1389b905c055eae74519b5',
    messagingSenderId: '432650534768',
    projectId: 'home-care-fb5a7',
    storageBucket: 'home-care-fb5a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFtdKMJ1OBQnZs1f52pc99F5puZ1oVL8',
    appId: '1:432650534768:ios:ed71accaab7a071d4519b5',
    messagingSenderId: '432650534768',
    projectId: 'home-care-fb5a7',
    storageBucket: 'home-care-fb5a7.appspot.com',
    iosBundleId: 'com.example.homeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFtdKMJ1OBQnZs1f52pc99F5puZ1oVL8',
    appId: '1:432650534768:ios:1a9d5c5abe077d924519b5',
    messagingSenderId: '432650534768',
    projectId: 'home-care-fb5a7',
    storageBucket: 'home-care-fb5a7.appspot.com',
    iosBundleId: 'com.example.homeCare.RunnerTests',
  );
}
